# Generated by Django 5.2.17 on 2026-08-27 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriStudytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_ke', models.IntegerField()),
                ('studytime', models.IntegerField()),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studytime_history', to='academic.matapelajaran')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studytime_history', to='academic.semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studytime_history', to='academic.siswa')),
            ],
            options={
                'db_table': 'histori_studytime',
            },
        ),
        migrations.CreateModel(
            name='NilaiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_ke', models.IntegerField()),
                ('jenis_evaluasi', models.CharField(choices=[('QUIZ', 'Quiz'), ('TUGAS', 'Tugas'), ('UTS', 'UTS'), ('UAS', 'UAS')], max_length=10)),
                ('nama_evaluasi', models.CharField(max_length=100)),
                ('skor', models.FloatField()),
                ('is_terlambat', models.BooleanField(default=False)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_list', to='academic.matapelajaran')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_list', to='academic.semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_list', to='academic.siswa')),
            ],
            options={
                'db_table': 'nilai_siswa',
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_ke', models.IntegerField()),
                ('risk_score', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')])),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='academic.matapelajaran')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='academic.semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='academic.siswa')),
            ],
            options={
                'db_table': 'prediction_result',
            },
        ),
        migrations.CreateModel(
            name='PresensiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_ke', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=10)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_list', to='academic.matapelajaran')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_list', to='academic.semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_list', to='academic.siswa')),
            ],
            options={
                'db_table': 'presensi_siswa',
            },
        ),
    ]
