# Generated by Django 5.2.17 on 2026-08-28 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historistudytime',
            options={'ordering': ['minggu_ke']},
        ),
        migrations.AlterModelOptions(
            name='nilaisiswa',
            options={'ordering': ['minggu_ke', 'id']},
        ),
        migrations.AlterModelOptions(
            name='predictionresult',
            options={'ordering': ['-minggu_ke', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='presensisiswa',
            options={'ordering': ['tanggal', 'minggu_ke']},
        ),
        migrations.AlterField(
            model_name='historistudytime',
            name='minggu_ke',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='historistudytime',
            name='studytime',
            field=models.IntegerField(help_text='Durasi belajar dalam jam per minggu'),
        ),
        migrations.AlterField(
            model_name='nilaisiswa',
            name='jenis_evaluasi',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('QUIZ2', 'Quiz2'), ('TUGAS', 'Tugas'), ('UTS', 'UTS'), ('UAS', 'UAS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nilaisiswa',
            name='minggu_ke',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='nilaisiswa',
            name='skor',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='minggu_ke',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='presensisiswa',
            name='minggu_ke',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AddIndex(
            model_name='historistudytime',
            index=models.Index(fields=['siswa', 'semester', 'minggu_ke'], name='histori_stu_siswa_i_d12429_idx'),
        ),
        migrations.AddIndex(
            model_name='historistudytime',
            index=models.Index(fields=['mapel', 'semester'], name='histori_stu_mapel_i_7a9ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='nilaisiswa',
            index=models.Index(fields=['siswa', 'semester'], name='nilai_siswa_siswa_i_6bb089_idx'),
        ),
        migrations.AddIndex(
            model_name='nilaisiswa',
            index=models.Index(fields=['mapel', 'semester', 'jenis_evaluasi'], name='nilai_siswa_mapel_i_97e3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['siswa', 'semester', 'risk_score'], name='prediction__siswa_i_28427b_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['mapel', 'semester', 'risk_score'], name='prediction__mapel_i_93de19_idx'),
        ),
        migrations.AddIndex(
            model_name='presensisiswa',
            index=models.Index(fields=['siswa', 'semester', 'status'], name='presensi_si_siswa_i_e0e185_idx'),
        ),
        migrations.AddIndex(
            model_name='presensisiswa',
            index=models.Index(fields=['mapel', 'semester', 'minggu_ke'], name='presensi_si_mapel_i_e98af8_idx'),
        ),
        migrations.AddConstraint(
            model_name='historistudytime',
            constraint=models.UniqueConstraint(fields=('siswa', 'mapel', 'semester', 'minggu_ke'), name='unique_studytime_per_week'),
        ),
        migrations.AddConstraint(
            model_name='predictionresult',
            constraint=models.UniqueConstraint(fields=('siswa', 'mapel', 'semester', 'minggu_ke'), name='unique_prediction_per_week'),
        ),
        migrations.AddConstraint(
            model_name='presensisiswa',
            constraint=models.UniqueConstraint(fields=('siswa', 'mapel', 'semester', 'tanggal'), name='unique_presensi_per_day_mapel'),
        ),
    ]
