# Generated by Django 5.2.17 on 2026-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_historistudytime_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='recommendation',
            field=models.JSONField(default=dict, help_text="Format JSON berisi rekomendasi multi-role: {'guru': '...', 'orangtua': '...', 'siswa': '...'}"),
        ),
    ]
