# Generated by Django 5.2.17 on 2026-08-27 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('is_aktif', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tahun_ajaran',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50)),
                ('wali_kelas', models.ForeignKey(blank=True, limit_choices_to={'role': 'GURU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_wali', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kelas',
            },
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mapel', models.CharField(max_length=20, unique=True)),
                ('nama_mapel', models.CharField(max_length=100)),
                ('pengajar', models.ForeignKey(blank=True, limit_choices_to={'role': 'GURU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapel_diajar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mata_pelajaran',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('nisn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('angkatan', models.IntegerField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_list', to='academic.kelas')),
                ('parent_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'ORANGTUA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anak_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'siswa',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_ke', models.IntegerField(choices=[(1, 'Ganjil'), (2, 'Genap')])),
                ('is_aktif', models.BooleanField(default=False)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.tahunajaran')),
            ],
            options={
                'db_table': 'semester',
            },
        ),
    ]
