# Generated by Django 5.2.17 on 2026-09-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='angkatan',
        ),
    ]
