# Generated by Django 5.2.17 on 2026-09-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_remove_siswa_angkatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='tanggal_mulai',
            field=models.DateField(default='2026-07-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
